### ISSUE TITLE
Meshgrid order issue when pre-calculating wavenumber with anisotropic grid.

### ISSUE THREAD

**Issue by linhz0hz** [wheelerMT/pygpe#11]
Hi, when using the package I found an issue when you create grid.wavenumber.
The wavenumber is created with numpy/cupy meshgrid, but you should specify indexing='ij' instead of indexing='xy' (default) in the following code:
`(
            self.fourier_x_mesh,
            self.fourier_y_mesh,
            self.fourier_z_mesh,
        ) = cp.meshgrid(fourier_x, fourier_y, fourier_z,indexing='ij')`

**Comment by wheelerMT** [comment]
Hi @linhz0hz! Good spot, I've been too focussed on isotropic grids I didn't realise. This is an issue for all created meshgrids, not just the wavenumber. I'll fix this shortly in a new PR.
